name: Build and publish

on:
  schedule:
    - cron: '0 18 * * *' # run at 6 PM UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u "vdeturckheimci" --password-stdin
    - run: node index.js
